name: ReUsable Workflow

on:
  workflow_dispatch:
    inputs:
      TARGET_ENVIRONMENT:
        description: "Target environment (dev, test, prod)"
        required: true
        default: test

jobs:
  run-reusable:
    uses: ./.github/workflows/reusable.yml
    with:
      target-environment: ${{ github.event.inputs.TARGET_ENVIRONMENT }}
